[packages]
alpine = [
  "delta",
  "drill",
  "exa",
]
windows = [
  "BurntSushi.ripgrep.MSVC",
  "Git.Git",
  "JesseDuffield.lazygit",
  "Microsoft.PowerShell",
  "Microsoft.Sysinternals.Autoruns",
  "Microsoft.Sysinternals.ProcessExplorer",
  "Microsoft.Sysinternals.ProcessMonitor",
  "Microsoft.Sysinternals.Sysmon",
  "Microsoft.VisualStudioCode.Insiders",
  "Microsoft.WindowsTerminal.Preview",
  "Mozilla.Firefox",
  "Neovim.Neovim",
  "Starship.Starship",
  "dandavison.delta",
  "gsass1.NTop",
  "jftuga.less",
  "junegunn.fzf",
  "sharkdp.fd",
  "voidtools.Everything",
]

[setupAnsible]
alpine = [
  "ansible",
  "ansible-lint"
]
