gitLogPretty    = "format:%C(auto)%h (%Cblue%al%Creset)%C(auto)%d %s"

[gitaliases]
ca   = "commit --amend --no-edit"
cb   = "checkout -b"
d    = "diff"
dc   = "diff --cached"
dcs  = "diff --cached --stat"
df   = "diff"
ds   = "diff --stat"
f    = "fetch --prune"
l    = "log"
p    = "push"
pf   = "push --force"
pl   = "pull"
r    = "rebase"
ra   = "rebase --abort"
rc   = "rebase --continue"
rs   = "rebase --skip"
s    = "status --short"

