[packages.mandatory]
7zip = { winget = "7zip.7zip" }
cascadia-code = { brew = "font-cascadia-code-nf" }
chezmoi = { unix = "chezmoi", winget = "twpayne.chezmoi" }
curl = { unix = "curl" }
drill = { alpine = "drill", chimera = "ldns" }
everything = { winget = "voidtools.Everything" }
eza = { unix = "eza" }
fd = { unix = "fd", winget = "sharkdp.fd" }
fzf = { unix = "fzf", winget = "junegunn.fzf" }
htop = { unix = "htop" }
jq = { unix = "jq" }
less = { unix = "less", winget = "jftuga.less" }
ripgrep = { unix = "ripgrep", winget = "BurntSushi.ripgrep.MSVC" }
rsync = { unix = "rsync" }
starship = { unix = "starship", winget = "Starship.Starship" }
strace = { linux = "strace" }
sysinternals = { winget = "Microsoft.Sysinternals.Suite" }
tcpdump = { unix = "tcpdump" }
unzip = { unix = "unzip" }
zsh = { unix = "zsh" }

[packages.optional]
alacritty = [{ unix = "alacritty", winget = "Alacritty.Alacritty" }]
ansible = [
  { unix = "ansible" },
  { mason = "ansible-language-server" },
  { mason = "ansible-lint" },
]
azure-cli = [{ brew = "azure-cli", winget = "Microsoft.AzureCLI" }]
buildtools = [
  { chimera = "clang" },
  { chimera = "cmake" },
  { chimera = "meson" },
  { chimera = "gmake" },
  { chimera = "pkgconf" },
  { chimera = "ninja" },
]
git = [
  { unix = "git", winget = "Git.Git" },
  { alpine = "git-crypt" },
  { brew = "git-delta", unix = "delta", winget = "dandavison.delta" }
]
neovim = [
  { unix = "neovim", winget = "Neovim.Neovim" },
  { chimera = "gcompat" },
  { chimera = "libgcc-chimera" },
  { linux = "tree-sitter-python" },
  { unix = "tree-sitter-cli" },
  { unix = "bash" },
  { mason = "stylua" },
  { mason = "beautysh" },
  { mason = "lua-language-server" },
  { mason = "tombi" },
  { unix = "wget" },  # needed for lua-language-server
]
niri = [
  { chimera = "niri" },
  { chimera = "quickshell" },
]
powershell = [{ brew = "powershell", winget = "Microsoft.PowerShell" }]
powershell-preview = [
  { brew = "powershell@preview", winget = "Microsoft.PowerShell.Preview" }
]
sway = [
  { chimera = "sway" },
  { chimera = "waybar" },
]
vscode = [
  { brew = "visual-studio-code", winget = "Microsoft.VisualStudioCode" }
]
vscode-insiders = [
  { brew = "visual-studio-code@insiders", winget = "Microsoft.VisualStudioCode.Insiders" }
]
mac-iterm2 = { brew = "iterm2" }
windows-hyperv = [
  { dism = "Containers-DisposableClientVM" },
  { dism = "Microsoft-Hyper-V" },
  { dism = "VirtualMachinePlatform" },
]
windows-terminal = { winget = "Microsoft.WindowsTerminal" }
windows-terminal-preview = { winget = "Microsoft.WindowsTerminal.Preview" }
wezterm = { unix = "wezterm", winget = "wez.wezterm" }
