[pkgDefs.mandatory]
cascadia-code = { brew = "font-cascadia-code-nf" }
curl = { unix = "curl" }
drill = { alpine = "drill", chimera = "ldns" }
everything = { winget = "voidtools.Everything" }
eza = { unix = "eza" }
fd = { unix = "fd", winget = "sharkdp.fd" }
fzf = { unix = "fzf", winget = "junegunn.fzf" }
htop = { unix = "htop" }
jq = { unix = "jq" }
less = { unix = "less", winget = "jftuga.less" }
pwsh = { winget = "Microsoft.PowerShell.Preview" }
ripgrep = { unix = "ripgrep", winget = "BurntSushi.ripgrep.MSVC" }
rsync = { unix = "rsync" }
starship = { unix = "starship", winget = "Starship.Starship" }
strace = { linux = "strace" }
sysinternals = { winget = "Microsoft.Sysinternals.Suite" }
tcpdump = { unix = "tcpdump" }
unzip = { unix = "unzip" }
vscode = { winget = "Microsoft.VisualStudioCode.Insiders" }
terminal = { brew = "iterm2", winget = "Microsoft.WindowsTerminal.Preview" }
zsh = { unix = "zsh" }

[pkgDefs.optional]
ansible = [
  { unix = "ansible" },
]

buildtools = [
  { chimera = "clang" },
  { chimera = "cmake" },
  { chimera = "meson" },
  { chimera = "gmake" },
]

git = [
  { unix = "git", winget = "Git.Git" },
  { alpine = "git-crypt" },
  { brew = "git-delta", unix = "delta", winget = "dandavison.delta" }
]

neovim = [
  { unix = "neovim", winget = "Neovim.Neovim" },
  { chimera = "gcompat" },
  { chimera = "libgcc-chimera" },
  { unix = "tree-sitter-python" },
  { unix = "tree-sitter-cli" },
  { unix = "bash" },
]
