font            = "Noto Sans"
monospaceFont   = "Cascadia Code NF"
gtkTheme        = "Catppuccin-Mocha-Standard-Sapphire-Dark"
iconTheme       = "Adwaita"
unixCursorTheme = "capitaine-cursors-light"
unixCursorSize  = "48"
xkbLayout       = "us,cz(qwerty)"
xkbLayoutLocked = "us"
xkbOptions      = "grp:lalt_lshift_toggle"
