"$schema" = "https://starship.rs/config-schema.json"
command_timeout = 100
format = "$directory$git_branch"

[directory]
style = ""
read_only = "\u200B"
read_only_style = ""

[git_branch]
format = "[$branch]($style)"
style = ""
